accounts/urls.py
from django.urls import path
from accounts.views import RegisterView, ProfileView
from django.contrib.auth import views as auth_views

app_name = 'accounts'
urlpatterns= [
    #punhub.net/accounts/login
    #pytpath('login/', LoginView, name='login'),
    #punhub.net/accounts/register
    path('register/', RegisterView.as_view() , name='register'),
    path('login/', auth_views.login, {'template_name':'accounts/login.html'},name='login'),
    path('logout/', auth_views.logout, {'next_page': '/'} ,name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
 ]

quicknote/urls.py
from django.urls import path
from .views.py import IndexView
app_name = 'quicknote'
urlpatterns = [

]

quiknotes/urls.py
from django.urls import path, include
from django.contrib import admin
from quicknote.views import IndexView

urlpatterns = [
    path('admin', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('accounts/', include('accounts.urls'))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class webUser(models.Model):
    User = models.OneToOneField(User, on_delete=models.CASCADE)

chat/models.py
from django.db import models
import json
from channels import Group


# Create your models here.
class Room(models.Model):
    id = models.CharField(max_length=20, primary_key=True, default="")
    display_name = models.CharField(max_length=20, default="")
    @property
    def websocket_group(self):
        return Group("room-%s" % self.id)

    def send_message(self, message, user):
        final_msg = {'room': str(self.id), 'message': message, 'username': user.username}

        self.websocket_group.send(
            {"text": json.dumps(final_msg)}
        )

quicknote/models.py
from django.db import models

accounts/forms.py
from django.forms import ModelForm
from accounts.models import webUser
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

accounts/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth import logout, login, authenticate
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
class RegisterView(generic.View):
    form_class = UserCreationForm
    template_name = 'accounts/register.html'
    def post(self,request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user=form.save()
            login(request,user)
            return HttpResponseRedirect(reverse('index'))
        else:
            return render(request, self.template_name, {'form': form, 'invalid': 'account invalid'})
    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form, 'invalid': ''})

@login_required
def logout_view(request):
    logout(request)

class ProfileView(generic.TemplateView):
    template_name = 'accounts/profile.html'

chat/views.py
from django.shortcuts import render

# Create your views here.

quicknote/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from accounts.models import webUser
from chat.models import Room

# Create your views here.
class IndexView(generic.TemplateView):

    rooms = Room.objects.order_by("display_name")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['rooms'] = self.rooms
        return context

    template_name = 'quicknote/index.html'





class SearchView(generic.ListView):

    model = webUser()

accounts/templates/accounts/login.html
{% extends 'quicknote/navbar.html' %}
{% block content %}
  <div class="jumbotron">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" class="btn btn-success" value="Login">
    </form>
  </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'quicknote/navbar.html' %}
{% block content %}
  <div class="jumbotron">
    <form action="" method="post">{% csrf_token %}
      {{ invalid }}
      {{ form.as_p }}
      <input class="btn btn-success" type="submit" value="Register!">
    </form>
  </div>

{% endblock %}

quicknote/templates/quicknote/index.html
{% extends 'quicknote/navbar.html' %}
{% block content %}
  <button id ='bigbutton' type="button" class="btn btn-outline-success btn-lg btn-block">Add Note</button>
      <div id='jumbojo' class="jumbotron" style="background=#FFE900 !important">
        <div class="container">
          <h1 class="display-2">Messager</h1>
        </div>
      </div>

{% endblock %}

quicknote/templates/quicknote/navbar.html
<!DOCTYPE html>

<html>
{% load staticfiles %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title></title>


  {# CSS #}

  {# JS #}

  {# BOOTSTRAP CSS #}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">

  {# BOOTSTRAP JS #}
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/js/bootstrap.min.js" integrity="sha384-a5N7Y/aK3qNeh15eJKGWxsqtnX/wWdSZSKp+81YjTmS15nvnvxKHuzaWwXHDli+4" crossorigin="anonymous"></script>

  {# My CSS and JS #}
  <link rel="stylesheet" href="{% static 'quicknote/main.css' %}">
  <script src='{% static "quicknote/main.js" %}'></script>

  {# Jquery #}
  <script
  src="https://code.jquery.com/jquery-3.3.0.min.js"
  integrity="sha256-RTQy8VOmNlT6b2PIRur37p6JEBZUE7o8wPgMvu18MC4="
  crossorigin="anonymous"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>

  {# CHAT CSS #}
  <link rel="stylesheet" href="{% static 'chat/main.css' %}">
  <script src='{% static "chat/chat.js" %}'></script>

</head>




{# BODY #}
<body>

  <nav id='navid' class="navbar navbar-dark bg-custom navbar-expand-lg" >
    {# BRAND #}


    <a class="navbar-brand" href="{% url 'index' %}">QUICKNOTES</a>



    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    {#COLLAPSE#}
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">

      {# left side #}
      <div class="navbar-nav">
        {# user info #}
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a> {% else %}
        <a class="nav-item nav-link" href="{% url 'accounts:register' %}">Register</a>
        <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a> {% endif %}
        <a class="nav-item nav-link disabled" href="#">Premium</a>
        <a href="#"></a>
      </div>


      {# right side #}
      <div class="navbar-nav ml-auto">
        <input class="form-control mr-sm-2" type="Search People" placeholder="Search" aria-label="Search">
        <div class="wrap">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </div>



      </div>
      <div class="wrap">
        <button type="button" id="sidebarCollapse" class="btn btn-outline-success navbar-btn">
        <i class="glyphicon glyphicon-align-left"></i>
        Chatbar
        </button>
      </div>

      {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'accounts:profile' %}">{{ user.get_username }}</a>
      {% endif %}

    </div>

  {# collapse #}
  </nav>
  {# navbar end #}

  {# NAVBARR #}


  <div class="wrapper">

    <div id="fontent">

      {% block content %} {% endblock %}

    </div>


    <nav id=sidebar>

      <div class="sidebar-header">
        <h5>Chatbar</h5>
      </div>

      <div class="sidebar-content">
        <ul id='roomsul'>
          {% for room in rooms %}
            <li class='room-link' data-room-id={{room.id}}>{{room.display_name}}</li>
          {% empty %}
            <p>no rooms available, maybe create one?</p>
          {% endfor %}

        </ul>


        <div id="chats">

        </div>


      </div>




    </nav>





  {# sidebar #}


  </div>
  {# wrapper end #}



</body>

</html>

quicknote/templates/quicknote/profile.html
{% extends 'navbar.html' %}
{% block content %}
  {% if user.is_authenticated %}
    <h1>{{user.user_name}}</h1>
  {% endif %}

{% endblock %}